# -*- coding: utf-8 -*-
"""Logistic_Regression_MScore_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oO-TUPO6IWdtQGzvCPrgFQTGaNUX_gHQ

# Logistic Regression dự báo gian lận BCTC

Notebook chạy trên Google Colab. Mô hình sử dụng 8 biến Beneish M-score, chia dữ liệu Train/Test theo tỷ lệ 80/20 và đánh giá bằng ma trận nhầm lẫn.
"""

# Logistic Regression dự báo gian lận BCTC - Google Colab
# Input: CSV gồm 8 biến Beneish + FRAUD_FLAG
# Chia train/test 80/20, chuẩn hóa trên train, đánh giá bằng Confusion Matrix.

import io
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix, ConfusionMatrixDisplay,
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report
)

# 1. Upload dữ liệu
print("Chọn file CSV của bạn, ví dụ: MScore_data.csv")
uploaded = files.upload()
csv_files = [k for k in uploaded if k.lower().endswith(".csv")]
if not csv_files:
    raise FileNotFoundError("Không tìm thấy file CSV.")
file_name = csv_files[0]
df = pd.read_csv(io.BytesIO(uploaded[file_name]))

print(f"Đã đọc: {file_name}")
print("Kích thước:", df.shape)
display(df.head())

# 2. Khai báo 8 biến Beneish và biến mục tiêu
FEATURES = ["DSRI", "GMI", "AQI", "SGI", "DEPI", "SGAI", "TATA", "LVGI"]
TARGET = "FRAUD_FLAG"

missing = [c for c in FEATURES + [TARGET] if c not in df.columns]
if missing:
    raise ValueError(f"Thiếu cột bắt buộc: {missing}")

# 3. Làm sạch dữ liệu
data = df[FEATURES + [TARGET]].copy()
for c in FEATURES + [TARGET]:
    data[c] = pd.to_numeric(data[c], errors="coerce")
data = data.dropna().reset_index(drop=True)
data[TARGET] = data[TARGET].astype(int)

if not set(data[TARGET].unique()).issubset({0, 1}):
    raise ValueError("FRAUD_FLAG phải có giá trị 0/1.")

print("\nPhân bố FRAUD_FLAG:")
print(data[TARGET].value_counts().sort_index())

# 4. Chia train/test 80/20
X = data[FEATURES]
y = data[TARGET]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print(f"Train: {len(X_train)} quan sát")
print(f"Test : {len(X_test)} quan sát")

# 5. Pipeline: chuẩn hóa -> Logistic Regression
model = Pipeline([
    ("scaler", StandardScaler()),
    ("logistic", LogisticRegression(max_iter=5000, random_state=42))
])

model.fit(X_train, y_train)

# 6. Hệ số mô hình
logistic = model.named_steps["logistic"]
intercept = logistic.intercept_[0]
coef = logistic.coef_[0]

coef_table = pd.DataFrame({
    "Hệ số": FEATURES,
    "Giá trị": coef,
    "Odds Ratio": np.exp(coef)
})

print("\n===== HỆ SỐ LOGISTIC =====")
print(f"Intercept = {intercept:.6f}")
display(coef_table)

# Phương trình (biến đã chuẩn hóa)
equation = f"logit(P(FRAUD=1)) = {intercept:.6f}"
for name, b in zip(FEATURES, coef):
    equation += f" {'+' if b >= 0 else '-'} {abs(b):.6f}*{name}_std"
print("\nPhương trình:")
print(equation)

# 7. Dự báo test
THRESHOLD = 0.50
y_prob = model.predict_proba(X_test)[:, 1]
y_pred = (y_prob >= THRESHOLD).astype(int)

# 8. Confusion Matrix
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
tn, fp, fn, tp = cm.ravel()

cm_table = pd.DataFrame(
    cm,
    index=["Thực tế: Không gian lận (0)", "Thực tế: Gian lận (1)"],
    columns=["Dự báo: Không gian lận (0)", "Dự báo: Gian lận (1)"]
)

print("\n===== MA TRẬN NHẦM LẪN =====")
display(cm_table)
print(f"TN={tn}, FP={fp}, FN={fn}, TP={tp}")

# 9. Chỉ tiêu từ confusion matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
specificity = tn / (tn + fp) if tn + fp else np.nan
fpr = fp / (fp + tn) if fp + tn else np.nan
fnr = fn / (fn + tp) if fn + tp else np.nan

metrics = pd.DataFrame({
    "Chỉ tiêu": [
        "Accuracy", "Precision", "Recall / Sensitivity",
        "F1-score", "Specificity",
        "False Positive Rate (FPR)", "False Negative Rate (FNR)"
    ],
    "Giá trị": [
        accuracy, precision, recall, f1,
        specificity, fpr, fnr
    ]
})
metrics["Giá trị (%)"] = metrics["Giá trị"] * 100

print("\n===== ĐÁNH GIÁ MÔ HÌNH =====")
display(metrics)

print("\n===== CLASSIFICATION REPORT =====")
print(classification_report(
    y_test, y_pred,
    target_names=["Không gian lận", "Gian lận"],
    zero_division=0, digits=4
))

# 10. Diễn giải hệ số
interpretation = []
for name, b in zip(FEATURES, coef):
    or_value = np.exp(b)
    if b > 0:
        meaning = (
            f"{name} tăng 1 độ lệch chuẩn làm tăng log-odds gian lận "
            f"{b:.4f}; odds gian lận được nhân {or_value:.4f}, "
            "giữ các biến khác không đổi."
        )
    elif b < 0:
        meaning = (
            f"{name} tăng 1 độ lệch chuẩn làm giảm log-odds gian lận "
            f"{abs(b):.4f}; odds gian lận được nhân {or_value:.4f}, "
            "giữ các biến khác không đổi."
        )
    else:
        meaning = f"{name} có hệ số bằng 0."
    interpretation.append({
        "Hệ số": name,
        "Giá trị": b,
        "Odds Ratio": or_value,
        "Ý nghĩa": meaning
    })

interpretation_table = pd.DataFrame(interpretation)

# 11. Vẽ confusion matrix
fig, ax = plt.subplots(figsize=(6, 5))
ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Không gian lận", "Gian lận"]
).plot(ax=ax, values_format="d", colorbar=False)
ax.set_title("Confusion Matrix - Logistic Regression")
ax.set_xlabel("Dự báo")
ax.set_ylabel("Thực tế")
plt.tight_layout()
plt.show()

# 12. Xuất toàn bộ kết quả ra Excel
output = "Logistic_Regression_MScore_Results.xlsx"
with pd.ExcelWriter(output, engine="openpyxl") as writer:
    coef_table.to_excel(writer, "Coefficients", index=False)
    cm_table.to_excel(writer, "Confusion_Matrix")
    metrics.to_excel(writer, "Metrics", index=False)
    interpretation_table.to_excel(writer, "Interpretation", index=False)

    pd.DataFrame({
        "Metric": ["Intercept", "Threshold", "Train_size", "Test_size"],
        "Value": [intercept, THRESHOLD, len(X_train), len(X_test)]
    }).to_excel(writer, "Model_Info", index=False)

print(f"\nĐã xuất: {output}")
files.download(output)

# 13. Tóm tắt
print("\n===== TÓM TẮT =====")
print(f"Accuracy  : {accuracy:.2%}")
print(f"Precision : {precision:.2%}")
print(f"Recall    : {recall:.2%}")
print(f"F1-score  : {f1:.2%}")
print(f"Specificity: {specificity:.2%}")
print(f"FPR       : {fpr:.2%}")
print(f"FNR       : {fnr:.2%}")